In [1]:
import pandas as pd
import numpy as np

In [2]:
app = pd.read_csv("playstore_apps.csv") # the app dataset with variable name app

In [3]:
app.head(100) #top 100 row

App           Category   
0      Photo Editor & Candy Camera & Grid & ScrapBook     ART_AND_DESIGN  \
1                                 Coloring book moana     ART_AND_DESIGN   
2   U Launcher Lite – FREE Live Cool Themes, Hide ...     ART_AND_DESIGN   
3                               Sketch - Draw & Paint     ART_AND_DESIGN   
4               Pixel Draw - Number Art Coloring Book     ART_AND_DESIGN   
..                                                ...                ...   
95  All of the parking lot - National Park applica...  AUTO_AND_VEHICLES   
96               Inquiry Fines and Debits of Vehicles  AUTO_AND_VEHICLES   
97                                        Gas Station  AUTO_AND_VEHICLES   
98                         Hush - Beauty for Everyone             BEAUTY   
99                     ipsy: Makeup, Beauty, and Tips             BEAUTY   

    Rating   Reviews  Size    Installs  Type  Price Content Rating   
0      4.1     159.0   19M     10000.0  Free    0.0       Everyone  \
1      3.9     967.0   14M    500000.0  Free    0.0       Everyone   
2      4.7   87510.0  8.7M   5000000.0  Free    0.0       Everyone   
3      4.5  215644.0   25M  50000000.0  Free    0.0           Teen   
4      4.3     967.0  2.8M    100000.0  Free    0.0       Everyone   
..     ...       ...   ...         ...   ...    ...            ...   
95     4.0    1754.0   14M    500000.0  Free    0.0       Everyone   
96     4.4    2680.0  2.2M    500000.0  Free    0.0       Everyone   
97     4.0    1288.0  4.5M    100000.0  Free    0.0       Everyone   
98     4.7   18900.0   17M    500000.0  Free    0.0       Everyone   
99     4.9   49790.0   14M   1000000.0  Free    0.0       Everyone   

                       Genres Last Updated         Current Ver   Android Ver  
0                Art & Design   07-01-2018               1.0.0  4.0.3 and up  
1   Art & Design;Pretend Play   15-01-2018               2.0.0  4.0.3 and up  
2                Art & Design   01-08-2018               1.2.4  4.0.3 and up  
3                Art & Design   08-06-2018  Varies with device    4.2 and up  
4     Art & Design;Creativity   20-06-2018                 1.1    4.4 and up  
..                        ...          ...                 ...           ...  
95            Auto & Vehicles   02-06-2018               2.3.4    4.0 and up  
96            Auto & Vehicles   20-03-2018                1.03  4.0.3 and up  
97            Auto & Vehicles   21-04-2018                2.17    4.0 and up  
98                     Beauty   02-08-2018              6.10.1    5.0 and up  
99                     Beauty   09-11-2017               2.3.0    4.1 and up  

[100 rows x 13 columns]

In [4]:
app.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   App             10841 non-null  object 
 1   Category        10841 non-null  object 
 2   Rating          9367 non-null   float64
 3   Reviews         10840 non-null  float64
 4   Size            10841 non-null  object 
 5   Installs        10840 non-null  float64
 6   Type            10840 non-null  object 
 7   Price           10840 non-null  float64
 8   Content Rating  10840 non-null  object 
 9   Genres          10841 non-null  object 
 10  Last Updated    10840 non-null  object 
 11  Current Ver     10833 non-null  object 
 12  Android Ver     10838 non-null  object 
dtypes: float64(4), object(9)
memory usage: 1.1+ MB


In [5]:
app.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [6]:
app_duplicates = app.duplicated().sum(); #check duplicates value inside dataset

In [7]:
print("duplicate No. of value",app_duplicates);

duplicate No. of value 483


In [8]:
#droping duplicate values present
app = app.drop_duplicates(keep='first');

In [9]:
app_duplicate = app.duplicated().sum();

In [10]:
#print(app_duplicate);
print(app.duplicated().sum());

0


In [11]:
app.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10358 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   App             10358 non-null  object 
 1   Category        10358 non-null  object 
 2   Rating          8893 non-null   float64
 3   Reviews         10357 non-null  float64
 4   Size            10358 non-null  object 
 5   Installs        10357 non-null  float64
 6   Type            10357 non-null  object 
 7   Price           10357 non-null  float64
 8   Content Rating  10357 non-null  object 
 9   Genres          10358 non-null  object 
 10  Last Updated    10357 non-null  object 
 11  Current Ver     10350 non-null  object 
 12  Android Ver     10355 non-null  object 
dtypes: float64(4), object(9)
memory usage: 1.1+ MB


In [12]:
app.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10358 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   App             10358 non-null  object 
 1   Category        10358 non-null  object 
 2   Rating          8893 non-null   float64
 3   Reviews         10357 non-null  float64
 4   Size            10358 non-null  object 
 5   Installs        10357 non-null  float64
 6   Type            10357 non-null  object 
 7   Price           10357 non-null  float64
 8   Content Rating  10357 non-null  object 
 9   Genres          10358 non-null  object 
 10  Last Updated    10357 non-null  object 
 11  Current Ver     10350 non-null  object 
 12  Android Ver     10355 non-null  object 
dtypes: float64(4), object(9)
memory usage: 1.1+ MB


In [13]:
app['Category'].unique()

array(['ART_AND_DESIGN', 'AUTO_AND_VEHICLES', 'BEAUTY',
       'BOOKS_AND_REFERENCE', 'BUSINESS', 'COMICS', 'COMMUNICATION',
       'DATING', 'EDUCATION', 'ENTERTAINMENT', 'EVENTS', 'FINANCE',
       'FOOD_AND_DRINK', 'HEALTH_AND_FITNESS', 'HOUSE_AND_HOME',
       'LIBRARIES_AND_DEMO', 'LIFESTYLE', 'GAME', 'FAMILY', 'MEDICAL',
       'SOCIAL', 'SHOPPING', 'PHOTOGRAPHY', 'SPORTS', 'TRAVEL_AND_LOCAL',
       'TOOLS', 'PERSONALIZATION', 'PRODUCTIVITY', 'PARENTING', 'WEATHER',
       'VIDEO_PLAYERS', 'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION',
       '1.9'], dtype=object)

In [14]:
app[app['Category']=='1.9']

App Category  Rating  Reviews   
10472  Life Made WI-Fi Touchscreen Photo Frame      1.9    19.0      NaN  \

         Size  Installs Type  Price Content Rating             Genres   
10472  1,000+       NaN    0    NaN            NaN  February 11, 2018  \

      Last Updated Current Ver Android Ver  
10472          NaN  4.0 and up         NaN

In [15]:
app = app[app['Category'] !='1.9']

In [16]:
app['Category'].unique()

array(['ART_AND_DESIGN', 'AUTO_AND_VEHICLES', 'BEAUTY',
       'BOOKS_AND_REFERENCE', 'BUSINESS', 'COMICS', 'COMMUNICATION',
       'DATING', 'EDUCATION', 'ENTERTAINMENT', 'EVENTS', 'FINANCE',
       'FOOD_AND_DRINK', 'HEALTH_AND_FITNESS', 'HOUSE_AND_HOME',
       'LIBRARIES_AND_DEMO', 'LIFESTYLE', 'GAME', 'FAMILY', 'MEDICAL',
       'SOCIAL', 'SHOPPING', 'PHOTOGRAPHY', 'SPORTS', 'TRAVEL_AND_LOCAL',
       'TOOLS', 'PERSONALIZATION', 'PRODUCTIVITY', 'PARENTING', 'WEATHER',
       'VIDEO_PLAYERS', 'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION'],
      dtype=object)

In [17]:
app_duplicate = app.duplicated().sum()

In [18]:
print(app_duplicate)

0


In [19]:
app['Rating'].unique()

array([4.1, 3.9, 4.7, 4.5, 4.3, 4.4, 3.8, 4.2, 4.6, 3.2, 4. , nan, 4.8,
       4.9, 3.6, 3.7, 3.3, 3.4, 3.5, 3.1, 5. , 2.6, 3. , 1.9, 2.5, 2.8,
       2.7, 1. , 2.9, 2.3, 2.2, 1.7, 2. , 1.8, 2.4, 1.6, 2.1, 1.4, 1.5,
       1.2])

In [20]:
app['Rating'] = app['Rating'].replace(np.nan,0);

In [21]:
app['Rating'].unique()

array([4.1, 3.9, 4.7, 4.5, 4.3, 4.4, 3.8, 4.2, 4.6, 3.2, 4. , 0. , 4.8,
       4.9, 3.6, 3.7, 3.3, 3.4, 3.5, 3.1, 5. , 2.6, 3. , 1.9, 2.5, 2.8,
       2.7, 1. , 2.9, 2.3, 2.2, 1.7, 2. , 1.8, 2.4, 1.6, 2.1, 1.4, 1.5,
       1.2])

In [22]:
app['Type'].unique()

array(['Free', 'Paid', nan], dtype=object)

In [23]:
app[app['Type'] == 'nan']

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver]
Index: []

In [24]:
app['Size'].unique()

array(['19M', '14M', '8.7M', '25M', '2.8M', '5.6M', '29M', '33M', '3.1M',
       '28M', '12M', '20M', '21M', '37M', '2.7M', '5.5M', '17M', '39M',
       '31M', '4.2M', '7.0M', '23M', '6.0M', '6.1M', '4.6M', '9.2M',
       '5.2M', '11M', '24M', 'Varies with device', '9.4M', '15M', '10M',
       '1.2M', '26M', '8.0M', '7.9M', '56M', '57M', '35M', '54M', '201k',
       '3.6M', '5.7M', '8.6M', '2.4M', '27M', '2.5M', '16M', '3.4M',
       '8.9M', '3.9M', '2.9M', '38M', '32M', '5.4M', '18M', '1.1M',
       '2.2M', '4.5M', '9.8M', '52M', '9.0M', '6.7M', '30M', '2.6M',
       '7.1M', '3.7M', '22M', '7.4M', '6.4M', '3.2M', '8.2M', '9.9M',
       '4.9M', '9.5M', '5.0M', '5.9M', '13M', '73M', '6.8M', '3.5M',
       '4.0M', '2.3M', '7.2M', '2.1M', '42M', '7.3M', '9.1M', '55M',
       '23k', '6.5M', '1.5M', '7.5M', '51M', '41M', '48M', '8.5M', '46M',
       '8.3M', '4.3M', '4.7M', '3.3M', '40M', '7.8M', '8.8M', '6.6M',
       '5.1M', '61M', '66M', '79k', '8.4M', '118k', '44M', '695k', '1.6M',
     

In [25]:
app['Installs'].unique()

array([1.e+04, 5.e+05, 5.e+06, 5.e+07, 1.e+05, 5.e+04, 1.e+06, 1.e+07,
       5.e+03, 1.e+08, 1.e+09, 1.e+03, 5.e+08, 5.e+01, 1.e+02, 5.e+02,
       1.e+01, 1.e+00, 5.e+00, 0.e+00])

In [26]:
app['Installs'] = app['Installs'].replace(np.nan,0);

In [27]:
app['Installs'].unique()

array([1.e+04, 5.e+05, 5.e+06, 5.e+07, 1.e+05, 5.e+04, 1.e+06, 1.e+07,
       5.e+03, 1.e+08, 1.e+09, 1.e+03, 5.e+08, 5.e+01, 1.e+02, 5.e+02,
       1.e+01, 1.e+00, 5.e+00, 0.e+00])

In [28]:
app['Installs'].value_counts()

Installs
1.000000e+06    1488
1.000000e+07    1132
1.000000e+05    1129
1.000000e+04    1033
1.000000e+03     890
1.000000e+02     710
5.000000e+06     683
5.000000e+05     517
5.000000e+04     474
5.000000e+03     469
1.000000e+01     385
1.000000e+08     369
5.000000e+02     328
5.000000e+07     272
5.000000e+01     204
5.000000e+00      82
1.000000e+00      67
5.000000e+08      61
1.000000e+09      49
0.000000e+00      15
Name: count, dtype: int64

In [29]:
app['Size'].value_counts()

Size
Varies with device    1526
11M                    188
13M                    186
12M                    186
14M                    182
                      ... 
430k                     1
429k                     1
200k                     1
460k                     1
619k                     1
Name: count, Length: 461, dtype: int64

In [30]:
app['Price'].unique()

array([  0.  ,   4.99,   3.99,   6.99,   1.49,   2.99,   7.99,   5.99,
         3.49,   1.99,   9.99,   7.49,   0.99,   9.  ,   5.49,  10.  ,
        24.99,  11.99,  79.99,  16.99,  14.99,   1.  ,  29.99,  12.99,
         2.49,  10.99,   1.5 ,  19.99,  15.99,  33.99,  74.99,  39.99,
         3.95,   4.49,   1.7 ,   8.99,   2.  ,   3.88,  25.99, 399.99,
        17.99, 400.  ,   3.02,   1.76,   4.84,   4.77,   1.61,   2.5 ,
         1.59,   6.49,   1.29,   5.  ,  13.99, 299.99, 379.99,  37.99,
        18.99, 389.99,  19.9 ,   8.49,   1.75,  14.  ,   4.85,  46.99,
       109.99, 154.99,   3.08,   2.59,   4.8 ,   1.96,  19.4 ,   3.9 ,
         4.59,  15.46,   3.04,   4.29,   2.6 ,   3.28,   4.6 ,  28.99,
         2.95,   2.9 ,   1.97, 200.  ,  89.99,   2.56,  30.99,   3.61,
       394.99,   1.26,   1.2 ,   1.04])

In [31]:
 #chek = len(app[app['Price]<0.0])
check = len(app[app['Price'] < 0.0])

In [32]:
print(check)

0


In [33]:
app['Current Ver'].isnull().sum()

8

In [34]:
app['Current Ver'] = app['Current Ver'].replace(np.nan,0)

In [35]:
app['Current Ver'].isnull().sum()

0

In [36]:
app['Current Ver'].unique()

array(['1.0.0', '2.0.0', '1.2.4', ..., '1.0.612928', '0.3.4', '2.0.148.0'],
      dtype=object)

In [37]:
len(app[app['Android Ver'] == 'Varies with device'])


1221

In [38]:
app = app[app['Android Ver'] != 'Varies with device']

In [39]:
app = app[app['Android Ver'].notnull()]

In [40]:
app[app['Android Ver'].isna()]

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver]
Index: []

In [41]:
app.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9134 entries, 0 to 10838
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   App             9134 non-null   object 
 1   Category        9134 non-null   object 
 2   Rating          9134 non-null   float64
 3   Reviews         9134 non-null   float64
 4   Size            9134 non-null   object 
 5   Installs        9134 non-null   float64
 6   Type            9134 non-null   object 
 7   Price           9134 non-null   float64
 8   Content Rating  9134 non-null   object 
 9   Genres          9134 non-null   object 
 10  Last Updated    9134 non-null   object 
 11  Current Ver     9134 non-null   object 
 12  Android Ver     9134 non-null   object 
dtypes: float64(4), object(9)
memory usage: 999.0+ KB


In [48]:
app['Last Updated']

0        07-01-2018
1        15-01-2018
2        01-08-2018
3        08-06-2018
4        20-06-2018
            ...    
10834    18-06-2017
10835    29-09-2016
10836    25-07-2017
10837    06-07-2018
10838    20-01-2017
Name: Last Updated, Length: 9134, dtype: object

In [51]:

app['Last Updated'] = pd.to_datetime(app['Last Updated'], format='%d-%m-%Y', errors='coerce')


app['Last Updated'] = app['Last Updated'].dt.strftime('%Y%m%d')


In [53]:
app.to_csv('playStore_apps_cleaned.csv')

In [57]:
num_rows_len = len(app);
print(num_rows_len)

9134


In [58]:
review = pd.read_csv("playstore_reviews.csv")

In [59]:
review.head()

App                                  Translated_Review   
0  10 Best Foods for You  I like eat delicious food. That's I'm cooking ...  \
1  10 Best Foods for You    This help eating healthy exercise regular basis   
2  10 Best Foods for You                                                NaN   
3  10 Best Foods for You         Works great especially going grocery store   
4  10 Best Foods for You                                       Best idea us   

  Sentiment  Sentiment_Polarity  Sentiment_Subjectivity  
0  Positive                1.00                0.533333  
1  Positive                0.25                0.288462  
2       NaN                 NaN                     NaN  
3  Positive                0.40                0.875000  
4  Positive                1.00                0.300000

In [60]:
review.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64295 entries, 0 to 64294
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   App                     64295 non-null  object 
 1   Translated_Review       37427 non-null  object 
 2   Sentiment               37432 non-null  object 
 3   Sentiment_Polarity      37432 non-null  float64
 4   Sentiment_Subjectivity  37432 non-null  float64
dtypes: float64(2), object(3)
memory usage: 2.5+ MB


In [61]:
review.columns

Index(['App', 'Translated_Review', 'Sentiment', 'Sentiment_Polarity',
       'Sentiment_Subjectivity'],
      dtype='object')

In [62]:
review['App'].unique()

array(['10 Best Foods for You', '104 找工作 - 找工作 找打工 找兼職 履歷健檢 履歷診療室',
       '11st', ..., 'Hotwire Hotel & Car Rental App',
       'Housing-Real Estate & Property', 'Houzz Interior Design Ideas'],
      dtype=object)

In [63]:
review[review['App'] == 'nan']

Empty DataFrame
Columns: [App, Translated_Review, Sentiment, Sentiment_Polarity, Sentiment_Subjectivity]
Index: []

In [64]:
duplicate = review.duplicated().sum()

In [65]:
print(duplicate)

33616


In [66]:
review.size

321475

In [67]:
review = review.drop_duplicates(keep = 'first')

In [68]:
review.duplicated().sum()

0

In [69]:
# Now data set is free of duplicate value

In [70]:
review[review['App'].isnull()]

Empty DataFrame
Columns: [App, Translated_Review, Sentiment, Sentiment_Polarity, Sentiment_Subjectivity]
Index: []

In [71]:
review[review['Translated_Review'].isnull()].head()

App Translated_Review   
2                               10 Best Foods for You               NaN  \
268                                              11st               NaN   
362                   1LINE – One Line with One Touch               NaN   
405  2018Emoji Keyboard 😂 Emoticons Lite -sticker&gif               NaN   
539               2Date Dating App, Love and matching               NaN   

    Sentiment  Sentiment_Polarity  Sentiment_Subjectivity  
2         NaN                 NaN                     NaN  
268   Neutral                 0.0                     0.0  
362       NaN                 NaN                     NaN  
405       NaN                 NaN                     NaN  
539       NaN                 NaN                     NaN

In [72]:
review = review[review['Translated_Review'].notnull()]

In [73]:
review['Sentiment'].unique()

array(['Positive', 'Neutral', 'Negative'], dtype=object)

In [74]:
review['Sentiment_Polarity'].unique()

array([ 1.        ,  0.25      ,  0.4       , ..., -0.52857143,
       -0.37777778,  0.17333333])

In [75]:
review['Sentiment_Subjectivity'].unique()

array([0.53333333, 0.28846154, 0.875     , ..., 0.51145833, 0.7172619 ,
       0.2594697 ])

In [76]:
review[review['Sentiment_Subjectivity'].isnull()].head()

Empty DataFrame
Columns: [App, Translated_Review, Sentiment, Sentiment_Polarity, Sentiment_Subjectivity]
Index: []

In [77]:
review.info()

<class 'pandas.core.frame.DataFrame'>
Index: 29692 entries, 0 to 64230
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   App                     29692 non-null  object 
 1   Translated_Review       29692 non-null  object 
 2   Sentiment               29692 non-null  object 
 3   Sentiment_Polarity      29692 non-null  float64
 4   Sentiment_Subjectivity  29692 non-null  float64
dtypes: float64(2), object(3)
memory usage: 1.4+ MB


In [78]:
review.head()

App                                  Translated_Review   
0  10 Best Foods for You  I like eat delicious food. That's I'm cooking ...  \
1  10 Best Foods for You    This help eating healthy exercise regular basis   
3  10 Best Foods for You         Works great especially going grocery store   
4  10 Best Foods for You                                       Best idea us   
5  10 Best Foods for You                                           Best way   

  Sentiment  Sentiment_Polarity  Sentiment_Subjectivity  
0  Positive                1.00                0.533333  
1  Positive                0.25                0.288462  
3  Positive                0.40                0.875000  
4  Positive                1.00                0.300000  
5  Positive                1.00                0.300000

In [81]:
review.to_csv('playStore_review_cleaned.csv')

In [ ]:
review.count()

App                       29692
Translated_Review         29692
Sentiment                 29692
Sentiment_Polarity        29692
Sentiment_Subjectivity    29692
dtype: int64

In [ ]:
# Both datasets were cleaned and stored in CSV file 